### ISSUE TITLE
editorKey

### ISSUE THREAD

**Issue by TheGoldMonkey** [BjornTheProgrammer/codemirror-collab-react-codemirror#2]
What does editorKey do here? Does it force a complete rerender of the component?

**Comment by BjornTheProgrammer** [comment]
Yeah, the `editorKey` variable's sole purpose is to force a complete rerender of the react-codemirror component. Due to the fact that react-codemirror contains it's own state which will cause issues when attempting to change the room to another. 

You can run the `multi-doc` branch deleting the `editorKey++;` line, and you'll notice that it completely stops working upon changing docs.

If you have any other questions, I would be happy to help.
